In [4]:
pip install aanalytics2

Requirement already satisfied: aanalytics2 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (0.2.6)
Requirement already satisfied: pathlib2 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (2.3.5)
Requirement already satisfied: pandas in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (1.0.5)
Requirement already satisfied: requests in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (2.24.0)
Requirement already satisfied: dicttoxml in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (1.7.4)
Requirement already satisfied: pathlib in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (1.0.1)
Requirement already satisfied: PyJWT in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (2.0.1)
Requirement already satisfied: pytest in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from aanalytics2) (5.4.3)
Requirement already satisfied: six in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pathlib2->aanalytics2) (1.15.0)
Requirement already satisfied: numpy>=1.13.3 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pandas->aanalytics2) (1.18.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pandas->aanalytics2) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pandas->aanalytics2) (2020.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from requests->aanalytics2) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from requests->aanalytics2) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from requests->aanalytics2) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from requests->aanalytics2) (3.0.4)
Requirement already satisfied: py>=1.5.0 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (1.9.0)
Requirement already satisfied: packaging in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (20.4)
Requirement already satisfied: attrs>=17.4.0 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (8.4.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (0.13.1)
Requirement already satisfied: wcwidth in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from pytest->aanalytics2) (0.2.5)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/adyg/opt/anaconda3/lib/python3.8/site-packages (from packaging->pytest->aanalytics2) (2.4.7)
Note: you may need to restart the kernel to use updated packages.

# 1 setup

In [19]:
import aanalytics2 as api2

In [20]:
api2.createConfigFile()

In [25]:
api2.importConfigFile('config_analytics_template.json')
#there is another way to add configuration through 'ap2.configure' method

In [31]:
# get company IDs
cids = api2.getCompanyId()
cids

[{'globalCompanyId': 'infinid',
  'companyName': 'Infiniti Helios Americas',
  'apiRateLimitPolicy': 'aa_api_tier10_tp',
  'dpc': 'lon'}]

In [ ]:
#updated code
#logger = api2.login == in order to create a login feature. 
#logger.COMPANY_IDS == lookup company id
#logger.getCompanyId() ==  use to get the companyID variable and pull it out for use
#logger.connector.config == this will give you the token variable also

In [32]:
# store company ID for INFINITI
cid = "infinid"

In [33]:
# allow the arguments to be used against your company id.
ags = api2.Analytics(cid)

In [37]:
# get the reporting suites

rsids = ags.getReportSuites()
rsids

,name,rsid
0,Infiniti US Production - T3 Retailer Sites (Vi...,vrs_infinid_infinitiusstagingt3r_0
1,Infiniti CA Staging,infiniticastaging
2,Infiniti US Staging - T3 Retailer Sites (Virtu...,vrs_infinid_infinitiusstagingt3r
3,Infiniti CA Prod,infiniticaprod
4,Infiniti US Production - IUSA (Virtual RS),vrs_infinid_infinitiusstagingius
5,Infiniti US Staging - IUSA (Virtual RS),vrs_infinid_infinitiusstagingt1
6,Infiniti US IP Exclusion,infinitiusipexclusion
7,Infiniti US Production,infinitiusprod
8,Infiniti US Staging,infinitiusstaging

In [42]:
# check format of rsid data frame. 

rsids.columns

Index(['name', 'rsid'], dtype='object')

In [43]:
# retrieving specific reporting suite

rsids.loc[0, 'rsid']

'vrs_infinid_infinitiusstagingt3r_0'

In [47]:
rsid = "vrs_infinid_infinitiusstagingius"

In [44]:
# check what is needed to pull the dimensions from a reporting suite. 

help (ags.getDimensions)

Help on method getDimensions in module aanalytics2.aanalytics2:

getDimensions(rsid: str, tags: bool = False, save=False, **kwargs) -> pandas.core.frame.DataFrame method of aanalytics2.aanalytics2.Analytics instance
    Retrieve the list of dimensions from a specific reportSuite.Shrink columns to simplify output.
    Returns the data frame of available dimensions.
    Arguments:
        rsid : REQUIRED : Report Suite ID from which you want the dimensions
        tags : OPTIONAL : If you would like to have additional information, such as tags. (bool : default False)
        save : OPTIONAL : If set to True, it will save the info in a csv file (bool : default False)
    Possible kwargs:
        full : Boolean : Doesn't shrink the number of columns if set to true
        example : getDimensions(rsid,full=True)

# 2 Dimensions

In [50]:
# extract the dimensions that are stored inside the specific reporting suite. 

dimensions = ags.getDimensions(rsid)

In [51]:
dimensions

,id,name,category,type,parent,pathable,description
0,variables/averagepagetime,Time Spent on Page - Bucketed,Metrics,ordered-enum,NaN,False,NaN
1,variables/browser,Browser,Audience,string,NaN,False,NaN
2,variables/browserheight,Browser Height - Granular,Audience,int,NaN,False,NaN
3,variables/browserheightbucketed,Browser Height - Bucketed,Audience,ordered-enum,NaN,False,NaN
4,variables/browsertype,Browser Type,Audience,enum,NaN,False,NaN
...,...,...,...,...,...,...,...
619,variables/visitpagenum,Visit Page Number,NaN,int,NaN,False,NaN
620,variables/visitstarttimegmt,Visit Start Time UTC,NaN,time,NaN,False,NaN
621,variables/weeklyuniquecustomers,Weekly Unique Customers,Customers,int,NaN,False,NaN
622,variables/yearlyuniquecustomers,Yearly Unique Customers,Customers,int,NaN,False,NaN
623,variables/zip,Zip Code,Audience,string,NaN,False,NaN

In [53]:
#clean view on transpose, in order to check the data.

dimensions.head(5).T

,0,1,2,3,4
id,variables/averagepagetime,variables/browser,variables/browserheight,variables/browserheightbucketed,variables/browsertype
name,Time Spent on Page - Bucketed,Browser,Browser Height - Granular,Browser Height - Bucketed,Browser Type
category,Metrics,Audience,Audience,Audience,Audience
type,ordered-enum,string,int,ordered-enum,enum
parent,NaN,NaN,NaN,NaN,NaN
pathable,False,False,False,False,False
description,NaN,NaN,NaN,NaN,NaN

In [54]:
#count of dimensions available 

len(dimensions)

624

In [56]:
#dimension types

dimensions['type'].unique()

array(['ordered-enum', 'string', 'int', 'enum', 'time'], dtype=object)

In [59]:
#dimension types in a list or tuple (fixed)

dimension_types = tuple(dimensions['type'].unique())
dimension_types

('ordered-enum', 'string', 'int', 'enum', 'time')

In [60]:
#count how many times the dimensions are used

dimensions['type'].value_counts()

string          533
enum             45
int              21
time             13
ordered-enum     12
Name: type, dtype: int64

In [62]:
#look at the dimension strings only. 

dimension_strings = dimensions[dimensions['type'] == 'string']
len(dimension_strings)
dimension_strings.head(10)

,id,name,category,type,parent,pathable,description
1,variables/browser,Browser,Audience,string,NaN,False,NaN
7,variables/campaign,Tracking Code,Traffic Sources,string,NaN,False,NaN
8,variables/campaign.1,Creative Elements,Traffic Sources,string,variables/campaign,False,NaN
9,variables/campaign.2,Campaigns,Traffic Sources,string,variables/campaign,False,NaN
10,variables/category,Category,Conversion,string,NaN,False,NaN
11,variables/clickmapaction,ClickMap Action (Legacy),NaN,string,NaN,False,NaN
12,variables/clickmapactiontype,ClickMap Action Type (Legacy),NaN,string,NaN,False,NaN
13,variables/clickmapcontext,ClickMap Context (Legacy),NaN,string,NaN,False,NaN
14,variables/clickmapcontexttype,ClickMap Context Type (Legacy),NaN,string,NaN,False,NaN
15,variables/clickmaplink,Activity Map Link,ClickMap,string,NaN,False,NaN

In [63]:
# how many types are null across the dimensions dataset

dimensions.isna().sum()

id               0
name             0
category        74
type             0
parent         515
pathable         0
description    610
dtype: int64

# 3 Segments

In [66]:
#get on the segments back

segments = ags.getSegments()

In [67]:
segments

,name,description,id,owner,migratedIds,rsid
0,55 | [H] e 74 exists,,s1008_57f29032e4b0d7f204619af4,{'id': 542881},[],infinitiusprod
1,InMX_ProductPage,This segment is used to know site performance ...,s1008_599ae89e01c1eb3a43a1626e,{'id': 611039},[],infinitimxprod
2,Untitled Segment,InMX_Prueba_de_Manejo,s1008_59cab8070f765a2495f0ab17,{'id': 611039},[],infinitimxprod
3,InMX_Prueba-de-manejo,Filtra pagename de prueba-de-manejo,s1008_59cab8ce366e5b07c280a73e,{'id': 611039},[],infinitimxprod
4,InMX_Confirmacion_prueba-de-manejo,PageName confirmación prueba-de-manejo,s1008_59cabd387245ec60b4f98db8,{'id': 611039},[],infinitimxprod
...,...,...,...,...,...,...
3939,Control navDisplay - TRUE (lm),,s1008_6083261c985bca4913a7d42b,{'id': 200252455},[],vrs_infinid_infinitiusstagingius
3940,SD Nav Display,,s1008_60871d6ce69aaa0d6037c52c,{'id': 200187676},[],vrs_infinid_infinitiusstagingius
3941,INFINITI: Content: VRS Overview excluding SD N...,,s1008_608720fbe9f45f5a4ca930b3,{'id': 200187676},[],vrs_infinid_infinitiusstagingius
3942,INFINITI: Qualified Visits - Ang,,s1008_60872903fc1a485aa1d38165,{'id': 200187676},[],vrs_infinid_infinitiusstagingius
3943,SD_Nav_Display Offer (lm),,s1008_60874300e69aaa0d6037c576,{'id': 200252455},[],vrs_infinid_infinitiusstagingius

In [74]:
# segments can usually use incorrect naming conventions and caused confusion. Pull extra info on the call
segments = ags.getSegments(extended_info = True)

In [75]:
segments

,name,description,modified,modifiedById,definition,compatibility,id,owner,migratedIds,rsid,tags,shares,reportSuiteName,siteTitle
0,55 | [H] e 74 exists,,2018-07-10T11:32:57Z,542881,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['event_metrics/event74', 'containe...",s1008_57f29032e4b0d7f204619af4,"{'id': 542881, 'name': 'Noemie Greyl', 'login'...",[],infinitiusprod,"[{'id': 17033, 'name': '55', 'components': []}...","[{'shareId': 1097409, 'shareToId': 569187, 'sh...",Infiniti US Production,Infiniti US Production
1,InMX_ProductPage,This segment is used to know site performance ...,2017-08-21T14:05:18Z,611039,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/page', 'conta...",s1008_599ae89e01c1eb3a43a1626e,"{'id': 611039, 'name': 'Ricardo Morales', 'log...",[],infinitimxprod,[],[],Infiniti MX Production,Infiniti MX Production
2,Untitled Segment,InMX_Prueba_de_Manejo,2017-09-26T20:26:47Z,611039,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/evar1', 'cont...",s1008_59cab8070f765a2495f0ab17,"{'id': 611039, 'name': 'Ricardo Morales', 'log...",[],infinitimxprod,[],[],Infiniti MX Production,Infiniti MX Production
3,InMX_Prueba-de-manejo,Filtra pagename de prueba-de-manejo,2017-09-26T20:40:11Z,611039,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/evar1', 'cont...",s1008_59cab8ce366e5b07c280a73e,"{'id': 611039, 'name': 'Ricardo Morales', 'log...",[],infinitimxprod,[],[],Infiniti MX Production,Infiniti MX Production
4,InMX_Confirmacion_prueba-de-manejo,PageName confirmación prueba-de-manejo,2017-09-26T20:48:56Z,611039,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/evar1', 'cont...",s1008_59cabd387245ec60b4f98db8,"{'id': 611039, 'name': 'Ricardo Morales', 'log...",[],infinitimxprod,[],[],Infiniti MX Production,Infiniti MX Production
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3939,Control navDisplay - TRUE (lm),,2021-04-23T20:19:40Z,200252455,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/prop53', 'con...",s1008_6083261c985bca4913a7d42b,"{'id': 200252455, 'name': 'Lianne MacLean', 'l...",[],vrs_infinid_infinitiusstagingius,[],[],Infiniti US Production - IUSA (Virtual RS),Infiniti US Production - IUSA (Virtual RS)
3940,SD Nav Display,,2021-04-26T22:41:39Z,200187676,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/prop53', 'con...",s1008_60871d6ce69aaa0d6037c52c,"{'id': 200187676, 'name': 'Angela Fu', 'login'...",[],vrs_infinid_infinitiusstagingius,[],[],Infiniti US Production - IUSA (Virtual RS),Infiniti US Production - IUSA (Virtual RS)
3941,INFINITI: Content: VRS Overview excluding SD N...,,2021-04-26T21:50:45Z,200187676,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/page', 'attri...",s1008_608720fbe9f45f5a4ca930b3,"{'id': 200187676, 'name': 'Angela Fu', 'login'...",[],vrs_infinid_infinitiusstagingius,[],[],Infiniti US Production - IUSA (Virtual RS),Infiniti US Production - IUSA (Virtual RS)
3942,INFINITI: Qualified Visits - Ang,,2021-04-26T21:52:34Z,200187676,"{'container': {'func': 'container', 'pred': {'...",{'schema': ['attribute_variables/averagepageti...,s1008_60872903fc1a485aa1d38165,"{'id': 200187676, 'name': 'Angela Fu', 'login'...",[],vrs_infinid_infinitiusstagingius,[],[],Infiniti US Production - IUSA (Virtual RS),Infiniti US Production - IUSA (Virtual RS)
3943,SD_Nav_Display Offer (lm),,2021-04-26T22:51:57Z,200252455,"{'container': {'func': 'container', 'pred': {'...","{'schema': ['attribute_variables/prop53', 'con...",s1008_60874300e69aaa0d6037c576,"{'id': 200252455, 'name': 'Lianne MacLean', 'l...",[],vrs_infinid_infinitiusstagingius,[],[],Infiniti US Production - IUSA (Virtual RS),Infiniti US Production - IUSA (Virtual RS)

In [76]:
#check to see which segments are duplicated. 

segments['def_string'] = segments['definition'].astype(str)

In [77]:
segments.duplicated('def_string')

0       False
1       False
2       False
3       False
4       False
        ...
3939    False
3940     True
3941    False
3942    False
3943     True
Length: 3944, dtype: bool

# Reports

In [79]:
# pull an existing report made in workspace. Not built for big report scales. 

myreport1 = ags.getReport('myreport1.json', verbose=True)

Request decrypted
Starting to fetch the data...
Data received.
last page status : True
% of total elements retrieved: 100.0 %
# of requests : 1
Report contains 100.0 % of the available dimensions

In [80]:
#call the report

myreport1

{'dimension': 'variables/daterangeday',
 'filters': {'globalFilters': ['2020-01-01T00:00:00.000/2021-01-01T00:00:00.000'],
  'metricsFilters': {'metrics/visits': {'s1008_59947e55a90b460d8299c104'},
   'cm1008_5cd9cc1b570d6874e5f950bb': {'s1008_59947e55a90b460d8299c104'}}},
 'rsid': 'vrs_infinid_infinitiusstagingius',
 'metrics': ['metrics/visits',
  'cm1008_5c9a8feeec2aba43a02a8274',
  'cm1008_5cd9cc1b570d6874e5f950bb',
  'metrics/visits',
  'cm1008_5cd9cc1b570d6874e5f950bb'],
 'data':     variables/daterangeday metrics/visits cm1008_5c9a8feeec2aba43a02a8274  \
 0              Jan 1, 2020          47968                           27797
 1              Jan 2, 2020          44815                           27253
 2              Jan 3, 2020          46199                           27024
 3              Jan 4, 2020          46726                           27862
 4              Jan 5, 2020          43828                           25821
 ..                     ...            ...                             ...
 361           Dec 27, 2020          71938                           33730
 362           Dec 28, 2020          74754                           35728
 363           Dec 29, 2020          71584                           34018
 364           Dec 30, 2020          73391                           34547
 365           Dec 31, 2020          61221                           28593

     cm1008_5cd9cc1b570d6874e5f950bb metrics/visits  \
 0                           0.57949           6036
 1                          0.608122            973
 2                          0.584948           4127
 3                          0.596285           4012
 4                          0.589144           4014
 ..                              ...            ...
 361                        0.468876           8783
 362                        0.477941           8345
 363                        0.475218           7912
 364                        0.470725           8084
 365                        0.467046           6939

     cm1008_5cd9cc1b570d6874e5f950bb
 0                          0.464049
 1                          0.326824
 2                          0.577902
 3                          0.590229
 4                          0.604634
 ..                              ...
 361                        0.457133
 362                        0.444458
 363                        0.451593
 364                        0.436789
 365                        0.416631

 [366 rows x 6 columns]}

In [81]:
#build the dataframe

data_report1= myreport1['data']

In [82]:
# call the dataframe

data_report1

,variables/daterangeday,metrics/visits,cm1008_5c9a8feeec2aba43a02a8274,cm1008_5cd9cc1b570d6874e5f950bb,metrics/visits,cm1008_5cd9cc1b570d6874e5f950bb
0,"Jan 1, 2020",47968,27797,0.57949,6036,0.464049
1,"Jan 2, 2020",44815,27253,0.608122,973,0.326824
2,"Jan 3, 2020",46199,27024,0.584948,4127,0.577902
3,"Jan 4, 2020",46726,27862,0.596285,4012,0.590229
4,"Jan 5, 2020",43828,25821,0.589144,4014,0.604634
...,...,...,...,...,...,...
361,"Dec 27, 2020",71938,33730,0.468876,8783,0.457133
362,"Dec 28, 2020",74754,35728,0.477941,8345,0.444458
363,"Dec 29, 2020",71584,34018,0.475218,7912,0.451593
364,"Dec 30, 2020",73391,34547,0.470725,8084,0.436789
365,"Dec 31, 2020",61221,28593,0.467046,6939,0.416631